name: Kitchen Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  kitchen-terraform:
    name: Kitchen-Terraform
    uses: osinfra-io/github-terraform-called-workflows/.github/workflows/kitchen-terraform.yml@brettcurtis/issue21
    with:
      service_account: testing-github-actions@shared-terraform-tf412f-sb.iam.gserviceaccount.com
      workload_identity_provider: projects/154948009703/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
